### PR TITLE
Ott realignment

### PR DESCRIPTION
**Pull request by MUCDK**
Updated pull request as discussed.

### CODE REVIEW

**Review by marcocuturi — COMMENTED** [review]
I think this looks alright! Maybe if you could make the changes suggested by Michal that could keep the pytype checker quiet that could be better. If you give this a try and resubmit I'll approve the PR.

**Comment by marcocuturi** [comment]
Thanks Dominik. I have imported the PR on the google side and have modified it. A few issues that were popping up were related to line length (should be <=80 characters), I have taken care of them!

Thanks.

**Review by marcocuturi — APPROVED** [review]
Thanks Dominik

**Comment by MUCDK** [comment]
Thank you very much Marco!

Am Fr., 7. Jan. 2022 um 12:13 Uhr schrieb marcocuturi <
***@***.***>:

**Pull request merged**
